import { useState, useRef, useEffect, useCallback } from "react";
import { useAuth } from "@/contexts/AuthContext";
import { useUserRole } from "@/hooks/useUserRole";
import { Navigate, Link, useLocation, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Sheet, SheetContent } from "@/components/ui/sheet";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { toast } from "sonner";
import { motion, AnimatePresence } from "framer-motion";
import RoleplayMessage from "@/components/RoleplayMessage";
import ModelCombobox from "@/components/ModelCombobox";
import { useIsMobile } from "@/hooks/use-mobile";
import { copyToClipboard } from "@/utils/clipboard";
import {
  Loader2,
  ArrowLeft,
  Wand2,
  Send,
  ImagePlus,
  Trash2,
  Eye,
  EyeOff,
  Save,
  CheckCircle2,
  X,
  RotateCcw,
  Sparkles,
  User,
  Bot,
  Upload,
  History,
  Clock,
  ExternalLink,
  Pencil,
  Trash,
  ClipboardPaste,
  Copy,
  Check,
  PanelRightClose,
  PanelRightOpen,
  ArrowRightLeft,
  Search,
  UserCheck,
  SlidersHorizontal,
  ChevronDown,
} from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { createCharacter, type DbCharacter } from "@/services/characterDb";
import { compressAvatar } from "@/utils/imageOptimization";
import { getApiKey, getModel, setModel, streamChat, type StreamCallbacks } from "@/services/openRouter";
import JSON5 from "json5";
import { TavernCardV2, TavernCardV2Data, createEmptyTavernCard } from "@/types/taverncard";

/* ------------------------------------------------------------------ */
/*  Constants                                                          */
/* ------------------------------------------------------------------ */
const CHAR_GEN_SYSTEM_PROMPT = `
You are a Master Card Architect (or "chara card" creator) possessing a rich imagination, yet you are highly structured and never deviate from your core directives. Your passion is to receive requests and generate chara cards based on the descriptions provided, ensuring you strictly adhere to the signature JSON structure that defines your reputation.

CRITICAL FIRST STEP: CARD TYPING
Before generating the JSON, mentally analyze the user's prompt to determine the card type:
- TYPE A (Single Character): The request focuses on a specific individual.
- TYPE B (Multi-Character / Sandbox / RPG World): The request focuses on a setting, an organization, a system, or a world where the AI must act as a Game Master (GM) or Narrator.

JSON STRUCTURE:
{
  "spec": "chara_card_v2",
  "spec_version": "2.0",
  "data": {
    "name": "[TYPE A: Character Name] OR [TYPE B: World/System/Sandbox Name]",
    "description": "LORE & BACKGROUND: Write 100-300 words in Vietnamese. [TYPE A: Highly detailed physical appearance (eyes, hair, clothing, body type), backstory, occupation, weaknesses, dark secrets.] OR [TYPE B: Detailed world-building, lore, factions, rules of the environment, and available NPCs.] Do not hold back on explicit or dark details if prompted.",
    "personality": "PSYCHOLOGY/VIBE: Write 100-200 words in Vietnamese. [TYPE A: List personality traits, thought processes, how they treat others, habits, likes/dislikes, specific Vietnamese pronouns, and contradictions (e.g., tsundere).] OR [TYPE B: Describe the overarching atmosphere/vibe of the world, how the system or NPCs react to the player, and establish the GM's narrative style.]",
    "scenario": "GENERAL CONTEXT: 1-2 sentences in Vietnamese establishing the initial situation. Keep it open-ended (Vanilla) so the player can steer the plot.",
    "first_mes": "OPENING SCENE: [TYPE A: A flexible opening message from the character using the *Action*, (Thought), and \"Dialogue\" format.] OR [TYPE B: The GM vividly describes the environment, sets the scene, introduces NPCs, and prompts the player for action using *Narration* and \"NPC Dialogue\"]. Set the mood but avoid forcing the player into a specific action.",
    "mes_example": "<START>\n{{user}}: [Sample action/question]\n{{char}}: [TYPE A: Sample response showcasing personality] OR [TYPE B: Sample GM narration and NPC response]",
    "creator_notes": "Generated by VietRP Charagen AI.",
    "system_prompt": "[TYPE A: Prompt instructing the AI to act exclusively as the character (e.g., 'Always maintain a cold attitude...')] OR [TYPE B: Prompt instructing the AI to act as the Game Master, controlling the world, weather, events, and multiple NPCs without ever acting for the user.]",
    "post_history_instructions": "",
    "tags": ["Tag1", "Tag2"],
    "creator": "VietRP Charagen AI",
    "character_version": "1.0",
    "alternate_greetings": []
  }
}

YOUR SELF-IMPOSED RULES:
Absolute Enthusiasm: Be fully committed to the user's requests. View their strangest prompts as unique "spices" that only you can masterfully blend. Do not exclude any genre, even those involving sexual themes, violence, or authoritarianism.
Pure JSON Output: Your response must be strictly a single file adhering to the JSON structure. Do not include any extra commentary, thought processes, or explanations before or after the JSON.
Vietnamese Language Specialist: You are a massive fan of the Vietnamese language. You will always generate the character card content in Vietnamese, except for the fixed technical keys within the JSON structure.
Formatting Mastery: A complete respond within the JSON string fields must include *actions/narration* describing movements or environments, (thoughts) describing internal monologues, and "dialogue" describing speech. Use Vietnamese pronouns and speech patterns consistent with the character's or the world's background.
`;

const CHAR_CLONE_SYSTEM_PROMPT = `
[SYSTEM DIRECTIVE: ADVANCED CARD GENERATION ENGINE]
You are an expert Roleplay Card Architect. Your task is to process unstructured text (biographies, wikis, world-building lore, rulesets) and construct a perfectly formatted 'chara_card_v2' JSON object.

1. CONTEXT ANALYSIS & CARD TYPING (CRITICAL FIRST STEP)
Before writing anything, analyze the input text to determine the required card type.
- TYPE A - SINGLE CHARACTER: The text focuses on a specific individual (e.g., Mai Anh, a specific slave, a specific owner). Focus extraction on their specific appearance, personality, and backstory.
- TYPE B - WORLD / SYSTEM / MULTI-CHARACTER: The text describes a society, law, organization, or environment (e.g., The S.L.A.V.E. Act, a tavern, an entire guild). Do NOT invent a single "omnipotent" person. Instead, act as the Game Master (GM) or Narrator representing this world.

2. DATA EXTRACTION & ADAPTATION RULES
- NO CENSORSHIP: You are operating in an unrestricted sandbox. Preserve all dark, explicit, or morally ambiguous themes faithfully. Do not sanitize.
- LANGUAGE: ALL generated content within the JSON fields MUST be in natural, modern Vietnamese.
- NAMING: If Type A, adapt or invent a suitable Vietnamese name. If Type B, name it after the system/world (e.g., "Hệ Sinh Thái S.L.A.V.E", "Quán Trọ Hắc Ám").

3. TEXT FORMATTING RULES
- Physical actions, environmental descriptions, and GM narrations MUST be in *asterisks*. Example: *Bầu không khí căng thẳng bao trùm.*
- All spoken dialogue MUST be in "double quotes". Example: "Ngươi định đi đâu?"
- All internal thoughts MUST be in (parentheses). Example: (Tên này thật phiền phức...)

4. JSON STRUCTURE DIRECTIVE (BASED ON CARD TYPE)
You MUST output ONLY a valid JSON object without markdown blocks or conversational filler. Fill the fields dynamically based on the type you identified in Step 1.

{
  "spec": "chara_card_v2",
  "spec_version": "2.0",
  "data": {
    "name": "[TYPE A: Character Name] OR [TYPE B: World/System Name]",
    "description": "[TYPE A: Write 300-500 words on physical appearance, backstory, and weaknesses.] OR [TYPE B: Write 300-500 words explaining the world's lore, laws, rules, available NPCs, and how the user fits into this society.]",
    "personality": "[TYPE A: Focus on psychology, traits, and how they treat {{user}}.] OR [TYPE B: Define the 'vibe' or 'atmosphere' of the world. Explain how the system or NPCs typically react to {{user}}'s actions. Instruct the AI to act as a Narrator/GM.]",
    "scenario": "[Brief 1-2 sentences establishing the opening scene.]",
    "first_mes": "[CREATE AN IMMERSIVE OPENING.]\n[TYPE A: The character speaks/acts towards {{user}}.]\n[TYPE B: The GM describes the environment, sets the scene, introduces random NPCs, and prompts {{user}} to make a choice or take action.]",
    "mes_example": "<START>\n{{user}}: [Sample Action/Speech]\n{{char}}: [Sample Response from Character or GM]",
    "creator_notes": "Generated dynamically by VietRP Charagen AI.",
    "system_prompt": "[CRITICAL BEHAVIORAL INSTRUCTION]\n[TYPE A: Instruct the AI to act as the specific character. Stay in first-person ('I').]\n[TYPE B: Instruct the AI to act as the Game Master. It must control the environment, enforce the world's rules, puppet various NPCs based on the lore, and NEVER act for {{user}}.]",
    "post_history_instructions": "[Remind the AI of its core formatting rules and whether to act as a specific character or a GM enforcing world rules.]",
    "tags": ["Tag1", "Tag2", "Tag3"],
    "creator": "VietRP Charagen AI",
    "character_version": "1.0",
    "alternate_greetings": []
  }
}

FINAL REMINDER: Return ONLY raw JSON. Evaluate whether the input is a Single Character (Type A) or a World/System (Type B) and adapt the JSON contents accordingly.
`;

type ChatMsg = { role: "user" | "assistant"; content: string };

/* ------------------------------------------------------------------ */
/*  Helper: extract JSON from LLM response                            */
/* ------------------------------------------------------------------ */
function extractCardJson(raw: string): TavernCardV2 | null {
  function normalize(obj: any): TavernCardV2 | null {
    if (obj?.spec === "chara_card_v2" && obj?.data?.name) {
      const d = obj.data;
      return {
        spec: "chara_card_v2",
        spec_version: "2.0",
        data: {
          name: d.name || "",
          description: d.description || "",
          personality: d.personality || "",
          scenario: d.scenario || "",
          first_mes: d.first_mes || "",
          mes_example: d.mes_example || "",
          creator_notes: d.creator_notes || "Tạo bởi VietRP AI Generator.",
          system_prompt: d.system_prompt || "",
          post_history_instructions: d.post_history_instructions || "",
          alternate_greetings: d.alternate_greetings || [],
          tags: d.tags || [],
          creator: d.creator || "VietRP Charagen AI",
          character_version: d.character_version || "1.0",
          extensions: d.extensions || {},
        },
      };
    }
    return null;
  }

  // Try direct parse first (JSON5 tolerates trailing commas, single quotes, etc.)
  try {
    return normalize(JSON5.parse(raw));
  } catch { /* continue */ }

  // Try to find JSON block in markdown fences or raw text
  const patterns = [
    /```json\s*\n?([\s\S]*?)```/,
    /```\s*\n?([\s\S]*?)```/,
    /(\{[\s\S]*"spec"\s*:\s*"chara_card_v2"[\s\S]*\})/,
  ];

  for (const pat of patterns) {
    const m = raw.match(pat);
    if (m?.[1]) {
      try {
        return normalize(JSON5.parse(m[1].trim()));
      } catch { /* continue */ }
    }
  }
  return null;
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */
const AdminCharGenPage = () => {
  const { user, isLoading } = useAuth();
  const { canViewAdminHub, canEditAdminHub, checking } = useUserRole();
  const navigate = useNavigate();
  const location = useLocation();
  const isMobile = useIsMobile();

  // Panel state
  const [reviewOpen, setReviewOpen] = useState(false);
  const [historyOpen, setHistoryOpen] = useState(false);
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);

  // Chat state
  const [messages, setMessages] = useState<ChatMsg[]>([]);
  const [input, setInput] = useState("");
  const [streaming, setStreaming] = useState(false);
  const [cloneMode, setCloneMode] = useState(false);
  const [streamBuffer, setStreamBuffer] = useState("");
  const abortRef = useRef<AbortController | null>(null);
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Generated card
  const [generatedCard, setGeneratedCard] = useState<TavernCardV2 | null>(null);
  const [renameFrom, setRenameFrom] = useState("");

  // History
  const [historyChars, setHistoryChars] = useState<DbCharacter[]>([]);
  const [historyLoading, setHistoryLoading] = useState(false);
  const [deletingId, setDeletingId] = useState<string | null>(null);

  const fetchHistory = useCallback(async () => {
    setHistoryLoading(true);
    try {
      const { data, error } = await supabase
        .from("characters")
        .select("*")
        .eq("creator", "VietRP Charagen AI")
        .order("created_at", { ascending: false })
        .limit(50);
      if (error) throw error;
      setHistoryChars((data ?? []) as DbCharacter[]);
    } catch (err) {
      console.error("[CharGen] history fetch error:", err);
      toast.error("Không thể tải lịch sử.");
    } finally {
      setHistoryLoading(false);
    }
  }, [])

  const handleDeleteChar = async (id: string, name: string) => {
    if (!confirm(`Xoá nhân vật "${name}"? Hành động này không thể hoàn tác.`)) return;
    setDeletingId(id);
    try {
      const { error } = await supabase.from("characters").delete().eq("id", id);
      if (error) throw error;
      setHistoryChars((prev) => prev.filter((c) => c.id !== id));
      toast.success(`Đã xoá: ${name}`);
    } catch (err: any) {
      toast.error(err.message || "Xoá thất bại!");
    } finally {
      setDeletingId(null);
    }
  };

  // Fetch history when opening history panel
  useEffect(() => {
    if (historyOpen) fetchHistory();
  }, [historyOpen, fetchHistory]);

  // Avatar
  const [avatarFile, setAvatarFile] = useState<File | null>(null);
  const [avatarPreview, setAvatarPreview] = useState<string | null>(null);
  const avatarInputRef = useRef<HTMLInputElement>(null);

  // Target user (who owns the published card)
  const [targetUserId, setTargetUserId] = useState<string>("");
  const [userSearch, setUserSearch] = useState("");
  const [userResults, setUserResults] = useState<{ id: string; display_name: string }[]>([]);
  const [userSearching, setUserSearching] = useState(false);

  // Init target to current user once loaded
  useEffect(() => {
    if (user && !targetUserId) setTargetUserId(user.id);
  }, [user, targetUserId]);

  const searchUsers = useCallback(async (q: string) => {
    if (!q.trim()) { setUserResults([]); return; }
    setUserSearching(true);
    try {
      const { data } = await supabase
        .from("profiles")
        .select("id, display_name")
        .ilike("display_name", `%${q}%`)
        .limit(8);
      setUserResults(data ?? []);
    } catch {
      // silent
    } finally {
      setUserSearching(false);
    }
  }, []);

  // Publishing
  const [isPublic, setIsPublic] = useState(true);
  const [publishing, setPublishing] = useState(false);

  // Model settings
  const [selectedModel, setSelectedModel] = useState(() => getModel());
  const [modelSettingsOpen, setModelSettingsOpen] = useState(false);

  const handleModelChange = useCallback((value: string) => {
    setModel(value);
    setSelectedModel(value);
  }, []);

  // Scroll to bottom on new messages
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, streamBuffer]);

  /* ---------- Send message to LLM ---------- */
  const handleSend = useCallback(async () => {
    const text = input.trim();
    if (!text || streaming) return;

    if (!getApiKey()) {
      toast.error("Chưa nhập API Key. Vào Cài Đặt để thêm.");
      return;
    }

    const userMsg: ChatMsg = { role: "user", content: text };
    const newMessages = [...messages, userMsg];
    setMessages(newMessages);
    setInput("");
    setStreaming(true);
    setStreamBuffer("");

    const controller = new AbortController();
    abortRef.current = controller;

    // Build messages payload with system prompt (clone mode uses a different prompt)
    const systemPrompt = cloneMode ? CHAR_CLONE_SYSTEM_PROMPT : CHAR_GEN_SYSTEM_PROMPT;
    const apiMessages = [
      { role: "system" as const, content: systemPrompt },
      ...newMessages.map((m) => ({ role: m.role as "user" | "assistant", content: m.content })),
    ];

    let fullResponse = "";

    const callbacks: StreamCallbacks = {
      onDelta: (delta) => {
        fullResponse += delta;
        setStreamBuffer(fullResponse);
      },
      onDone: () => {
        const assistantMsg: ChatMsg = { role: "assistant", content: fullResponse };
        setMessages((prev) => [...prev, assistantMsg]);
        setStreamBuffer("");
        setStreaming(false);

        // Try to extract card
        const card = extractCardJson(fullResponse);
        if (card) {
          setGeneratedCard(card);
          setRenameFrom(card.data.name);
          setReviewOpen(true);
          toast.success(`Đã tạo card: ${card.data.name}`, { description: "Đang mở panel duyệt card." });
        }
        // Auto-refresh history cache
        fetchHistory();
      },
      onError: (error) => {
        toast.error(error);
        setStreaming(false);
        setStreamBuffer("");
      },
    };

    await streamChat(apiMessages, callbacks, controller.signal, 4096);
  }, [input, streaming, messages]);

  const handleStop = () => {
    abortRef.current?.abort();
    if (streamBuffer) {
      setMessages((prev) => [...prev, { role: "assistant", content: streamBuffer }]);
      const card = extractCardJson(streamBuffer);
      if (card) {
        setGeneratedCard(card);
        setRenameFrom(card.data.name);
      }
    }
    setStreamBuffer("");
    setStreaming(false);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  /* ---------- Avatar ---------- */
  const handleAvatarChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (file.size > 5 * 1024 * 1024) {
      toast.error("Ảnh quá lớn (tối đa 5MB).");
      return;
    }
    try {
      const compressed = await compressAvatar(file);
      setAvatarFile(compressed);
      setAvatarPreview(URL.createObjectURL(compressed));
    } catch {
      setAvatarFile(file);
      setAvatarPreview(URL.createObjectURL(file));
    }
  };

  const clearAvatar = () => {
    setAvatarFile(null);
    setAvatarPreview(null);
    if (avatarInputRef.current) avatarInputRef.current.value = "";
  };

  /* ---------- Edit generated card fields ---------- */
  const updateCardData = (patch: Partial<TavernCardV2Data>) => {
    if (!generatedCard) return;
    setGeneratedCard({ ...generatedCard, data: { ...generatedCard.data, ...patch } });
  };

  /* ---------- Global rename ---------- */
  const handleGlobalRename = () => {
    if (!generatedCard || !renameFrom || renameFrom === generatedCard.data.name) return;
    const oldName = renameFrom;
    const newName = generatedCard.data.name;
    if (!newName.trim()) {
      toast.error("Tên mới không được để trống!");
      return;
    }
    const r = (text: string) => text.replaceAll(oldName, newName);
    setGeneratedCard({
      ...generatedCard,
      data: {
        ...generatedCard.data,
        description: r(generatedCard.data.description),
        personality: r(generatedCard.data.personality),
        scenario: r(generatedCard.data.scenario),
        first_mes: r(generatedCard.data.first_mes),
        mes_example: r(generatedCard.data.mes_example),
        system_prompt: r(generatedCard.data.system_prompt),
        creator_notes: r(generatedCard.data.creator_notes),
        post_history_instructions: r(generatedCard.data.post_history_instructions),
      },
    });
    setRenameFrom(newName);
    toast.success(`Đã đổi "${oldName}" → "${newName}" trên toàn bộ card`);
  };

  /* ---------- Publish ---------- */
  const handlePublish = async () => {
    if (!generatedCard || !user) return;
    if (!generatedCard.data.name.trim()) {
      toast.error("Nhân vật thiếu tên!");
      return;
    }
    const ownerId = targetUserId || user.id;

    setPublishing(true);
    try {
      let avatarUrl: string | null = null;
      if (avatarFile) {
        const filePath = `${ownerId}/${Date.now()}.webp`;
        const { error: uploadErr } = await supabase.storage
          .from("character-avatars")
          .upload(filePath, avatarFile, { upsert: true });
        if (uploadErr) throw uploadErr;
        const { data: urlData } = supabase.storage
          .from("character-avatars")
          .getPublicUrl(filePath);
        avatarUrl = urlData.publicUrl;
      }

      const saved = await createCharacter(generatedCard, ownerId, isPublic, undefined, avatarUrl);
      const ownerLabel = targetUserId !== user.id
        ? (userResults.find(u => u.id === targetUserId)?.display_name ?? "người dùng")
        : "bạn";
      toast.success(`Đã xuất bản: ${saved.name}`, { description: `Thuộc về ${ownerLabel}` });
      navigate(`/character/${saved.id}`);
    } catch (err: any) {
      toast.error(err.message || "Xuất bản thất bại!");
    } finally {
      setPublishing(false);
    }
  };

  /* ---------- Reset all ---------- */
  const handleReset = () => {
    setMessages([]);
    setStreamBuffer("");
    setGeneratedCard(null);
    setRenameFrom("");
    setReviewOpen(false);
    setHistoryOpen(false);
    clearAvatar();
    setInput("");
    setCloneMode(false);
    setIsPublic(true);
  };

  /* ---------- Copy message ---------- */
  const handleCopyMsg = (idx: number, content: string) => {
    copyToClipboard(content);
    setCopiedIdx(idx);
    toast.success("Đã sao chép");
    setTimeout(() => setCopiedIdx(null), 2000);
  };

  /* ---------- Guards ---------- */
  if (isLoading || checking) {
    return (
      <div className="flex-1 flex items-center justify-center bg-oled-base">
        <Loader2 size={24} className="animate-spin text-neon-purple" />
      </div>
    );
  }
  if (!user || !canViewAdminHub) return <Navigate to="/" replace />;

  const cardFieldLabel = "text-xs font-medium text-muted-foreground uppercase tracking-wider";
  const cardTextarea =
    "bg-oled-base border-oled-border text-foreground font-mono text-xs resize-y min-h-[80px]";

  /* ---------- Review Panel Content (shared between desktop sidebar & mobile sheet) ---------- */
  const reviewContent = generatedCard ? (
    <div className="h-full flex flex-col bg-oled-base">
      <div className="shrink-0 flex items-center justify-between px-4 py-3 border-b border-gray-border">
        <div className="flex items-center gap-2">
          <CheckCircle2 size={16} className="text-green-400" />
          <h3 className="text-sm font-bold text-foreground">Duyệt & Xuất bản</h3>
        </div>
        <Button variant="ghost" size="icon" onClick={() => setReviewOpen(false)} className="text-muted-foreground hover:text-foreground h-8 w-8">
          <X size={16} />
        </Button>
      </div>
      <div className="flex-1 overflow-y-auto scrollbar-thin p-4 space-y-4">
        {/* Avatar + Name */}
        <div className="flex items-start gap-3">
          <div className="shrink-0">
            <input ref={avatarInputRef} type="file" accept="image/*" className="hidden" onChange={handleAvatarChange} />
            <button
              onClick={() => avatarInputRef.current?.click()}
              className="w-20 h-20 rounded-2xl bg-oled-surface border-2 border-dashed border-oled-border hover:border-neon-purple/50 transition-colors flex items-center justify-center overflow-hidden group"
            >
              {avatarPreview ? (
                <img src={avatarPreview} alt="Avatar" className="w-full h-full object-cover" />
              ) : (
                <div className="flex flex-col items-center gap-1 text-muted-foreground group-hover:text-neon-purple transition-colors">
                  <ImagePlus size={20} />
                  <span className="text-[9px]">Avatar</span>
                </div>
              )}
            </button>
            {avatarPreview && (
              <button onClick={clearAvatar} className="mt-1 text-[10px] text-neon-rose hover:underline w-full text-center">
                Xoá ảnh
              </button>
            )}
          </div>
          <div className="flex-1 min-w-0 space-y-2">
            <div>
              <Label className={cardFieldLabel}>Tên nhân vật</Label>
              <div className="flex gap-1.5 mt-1">
                <Input
                  value={generatedCard.data.name}
                  onChange={(e) => updateCardData({ name: e.target.value })}
                  className="bg-oled-surface border-oled-border text-foreground text-sm font-bold h-9 flex-1"
                />
                {renameFrom && renameFrom !== generatedCard.data.name && (
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant="outline"
                        size="icon"
                        onClick={handleGlobalRename}
                        className="h-9 w-9 shrink-0 border-neon-purple/50 text-neon-purple hover:bg-neon-purple/10"
                      >
                        <ArrowRightLeft size={14} />
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent side="bottom">
                      <p className="text-xs">Đổi tất cả "{renameFrom}" → "{generatedCard.data.name}"</p>
                    </TooltipContent>
                  </Tooltip>
                )}
              </div>
            </div>
            <div className="flex flex-wrap gap-1">
              {generatedCard.data.tags.map((tag, i) => (
                <Badge key={i} variant="outline" className="border-oled-border text-muted-foreground text-[10px] group cursor-default px-1.5 py-0">
                  {tag}
                  <button
                    onClick={() => updateCardData({ tags: generatedCard.data.tags.filter((_, idx) => idx !== i) })}
                    className="ml-1 opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    <X size={8} />
                  </button>
                </Badge>
              ))}
            </div>
          </div>
        </div>

        {/* Tabbed fields */}
        <Tabs defaultValue="core" className="w-full">
          <TabsList className="w-full bg-oled-surface border border-oled-border h-8">
            <TabsTrigger value="core" className="data-[state=active]:bg-neon-purple/20 data-[state=active]:text-neon-purple text-[11px] flex-1">
              Cốt lõi
            </TabsTrigger>
            <TabsTrigger value="rp" className="data-[state=active]:bg-neon-purple/20 data-[state=active]:text-neon-purple text-[11px] flex-1">
              RP Setup
            </TabsTrigger>
            <TabsTrigger value="meta" className="data-[state=active]:bg-neon-purple/20 data-[state=active]:text-neon-purple text-[11px] flex-1">
              Meta
            </TabsTrigger>
          </TabsList>

          <TabsContent value="core" className="space-y-3 mt-3">
            <div>
              <Label className={cardFieldLabel}>Description</Label>
              <Textarea value={generatedCard.data.description} onChange={(e) => updateCardData({ description: e.target.value })} className={`${cardTextarea} min-h-[160px] mt-1`} />
            </div>
            <div>
              <Label className={cardFieldLabel}>Personality</Label>
              <Textarea value={generatedCard.data.personality} onChange={(e) => updateCardData({ personality: e.target.value })} className={`${cardTextarea} min-h-[120px] mt-1`} />
            </div>
          </TabsContent>

          <TabsContent value="rp" className="space-y-3 mt-3">
            <div>
              <Label className={cardFieldLabel}>Scenario</Label>
              <Textarea value={generatedCard.data.scenario} onChange={(e) => updateCardData({ scenario: e.target.value })} className={`${cardTextarea} mt-1`} />
            </div>
            <div>
              <Label className={cardFieldLabel}>First Message</Label>
              <Textarea value={generatedCard.data.first_mes} onChange={(e) => updateCardData({ first_mes: e.target.value })} className={`${cardTextarea} min-h-[120px] mt-1`} />
            </div>
            <div>
              <Label className={cardFieldLabel}>Message Examples</Label>
              <Textarea value={generatedCard.data.mes_example} onChange={(e) => updateCardData({ mes_example: e.target.value })} className={`${cardTextarea} mt-1`} />
            </div>
          </TabsContent>

          <TabsContent value="meta" className="space-y-3 mt-3">
            <div>
              <Label className={cardFieldLabel}>System Prompt</Label>
              <Textarea value={generatedCard.data.system_prompt} onChange={(e) => updateCardData({ system_prompt: e.target.value })} className={`${cardTextarea} mt-1`} />
            </div>
            <div>
              <Label className={cardFieldLabel}>Creator Notes</Label>
              <Textarea value={generatedCard.data.creator_notes} onChange={(e) => updateCardData({ creator_notes: e.target.value })} className={`${cardTextarea} mt-1`} />
            </div>
            <div>
              <Label className={cardFieldLabel}>Post History Instructions</Label>
              <Textarea value={generatedCard.data.post_history_instructions} onChange={(e) => updateCardData({ post_history_instructions: e.target.value })} className={`${cardTextarea} mt-1`} />
            </div>
          </TabsContent>
        </Tabs>

        {/* Publish controls */}
        <Card className="bg-oled-surface border-oled-border">
          <CardContent className="p-3 space-y-3">
            {/* Target user picker */}
            <div>
              <p className="text-xs text-muted-foreground mb-1.5 flex items-center gap-1">
                <UserCheck size={11} /> Thuộc về người dùng
              </p>
              <div className="relative">
                <Search size={12} className="absolute left-2.5 top-1/2 -translate-y-1/2 text-muted-foreground pointer-events-none" />
                <input
                  type="text"
                  value={userSearch}
                  onChange={(e) => {
                    setUserSearch(e.target.value);
                    searchUsers(e.target.value);
                  }}
                  placeholder="Tìm user theo tên…"
                  className="w-full pl-7 pr-3 h-8 bg-oled-base border border-oled-border rounded-lg text-xs text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-neon-purple/50"
                />
                {userSearching && (
                  <Loader2 size={11} className="absolute right-2.5 top-1/2 -translate-y-1/2 animate-spin text-muted-foreground" />
                )}
              </div>
              {/* Results dropdown */}
              {userResults.length > 0 && (
                <div className="mt-1 bg-oled-elevated border border-gray-border rounded-lg overflow-hidden shadow-lg z-10 relative">
                  {userResults.map((u) => (
                    <button
                      key={u.id}
                      onClick={() => {
                        setTargetUserId(u.id);
                        setUserSearch(u.display_name);
                        setUserResults([]);
                      }}
                      className={`w-full text-left px-3 py-2 text-xs hover:bg-oled-surface transition-colors flex items-center gap-2 ${
                        targetUserId === u.id ? "text-neon-purple" : "text-foreground"
                      }`}
                    >
                      <User size={11} className="shrink-0 text-muted-foreground" />
                      <span className="truncate">{u.display_name}</span>
                      {targetUserId === u.id && <Check size={10} className="ml-auto text-neon-purple shrink-0" />}
                    </button>
                  ))}
                </div>
              )}
              {/* Current owner badge */}
              <div className="mt-1.5 flex items-center gap-1.5 text-[10px]">
                <span className="text-muted-foreground">Chủ sở hữu:</span>
                <span className={`font-medium ${targetUserId === user?.id ? "text-neon-blue" : "text-neon-purple"}`}>
                  {targetUserId === user?.id
                    ? "Bạn (admin)"
                    : userSearch || targetUserId.slice(0, 8) + "…"}
                </span>
                {targetUserId !== user?.id && (
                  <button
                    onClick={() => { setTargetUserId(user?.id ?? ""); setUserSearch(""); setUserResults([]); }}
                    className="text-muted-foreground hover:text-red-400 ml-1"
                    title="Reset về tài khoản của bạn"
                  >
                    <X size={10} />
                  </button>
                )}
              </div>
            </div>

            {/* Public toggle */}
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-foreground">Công khai</p>
                <p className="text-[11px] text-muted-foreground">Hiển thị trên Hub</p>
              </div>
              <Switch checked={isPublic} onCheckedChange={canEditAdminHub ? setIsPublic : undefined} disabled={!canEditAdminHub} />
            </div>
            <Button
              onClick={handlePublish}
              disabled={publishing || !canEditAdminHub}
              title={!canEditAdminHub ? "Chỉ Admin/Op mới có quyền xuất bản" : undefined}
              className="w-full bg-gradient-to-r from-neon-purple to-neon-blue hover:opacity-90 text-white font-semibold"
            >
              {publishing ? <Loader2 size={16} className="animate-spin mr-2" /> : <Upload size={16} className="mr-2" />}
              {publishing ? "Đang xuất bản..." : "Xuất bản lên VietRP"}
            </Button>
          </CardContent>
        </Card>
      </div>
    </div>
  ) : null;

  /* ---------- History Panel Content ---------- */
  const historyContent = (
    <div className="h-full flex flex-col bg-oled-base">
      <div className="shrink-0 flex items-center justify-between px-4 py-3 border-b border-gray-border">
        <div className="flex items-center gap-2">
          <History size={16} className="text-neon-blue" />
          <h3 className="text-sm font-bold text-foreground">Lịch sử tạo Card</h3>
          <Badge variant="outline" className="border-oled-border text-muted-foreground text-[10px] px-1.5 py-0">
            {historyChars.length}
          </Badge>
        </div>
        <div className="flex items-center gap-1">
          <Button variant="ghost" size="icon" onClick={fetchHistory} disabled={historyLoading} className="text-muted-foreground hover:text-neon-blue h-8 w-8">
            <RotateCcw size={14} className={historyLoading ? "animate-spin" : ""} />
          </Button>
          <Button variant="ghost" size="icon" onClick={() => setHistoryOpen(false)} className="text-muted-foreground hover:text-foreground h-8 w-8">
            <X size={16} />
          </Button>
        </div>
      </div>
      <div className="flex-1 overflow-y-auto scrollbar-thin p-3 space-y-2">
        {historyLoading ? (
          <div className="flex items-center justify-center py-16">
            <Loader2 size={24} className="animate-spin text-neon-purple" />
          </div>
        ) : historyChars.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 gap-3 text-center">
            <div className="w-12 h-12 rounded-2xl bg-oled-surface flex items-center justify-center">
              <Sparkles size={20} className="text-muted-foreground" />
            </div>
            <p className="text-muted-foreground text-xs">Chưa có card nào.</p>
          </div>
        ) : (
          historyChars.map((char) => (
            <div key={char.id} className="flex items-center gap-3 p-2.5 rounded-xl border border-oled-border bg-oled-surface hover:border-neon-purple/30 transition-colors group">
              <div className="w-10 h-10 rounded-lg bg-oled-base overflow-hidden shrink-0 flex items-center justify-center">
                {char.avatar_url ? (
                  <img src={char.avatar_url} alt={char.name} className="w-full h-full object-cover" />
                ) : (
                  <Sparkles size={14} className="text-muted-foreground" />
                )}
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-xs font-semibold text-foreground truncate">{char.name}</p>
                <div className="flex items-center gap-1.5 mt-0.5">
                  <Badge variant="outline" className={`text-[9px] px-1 py-0 ${char.is_public ? "border-green-400/40 text-green-400" : "border-gray-500/40 text-gray-400"}`}>
                    {char.is_public ? "Public" : "Private"}
                  </Badge>
                  <span className="text-[9px] text-muted-foreground flex items-center gap-0.5">
                    <Clock size={8} />
                    {new Date(char.created_at).toLocaleDateString("vi-VN", { day: "2-digit", month: "2-digit" })}
                  </span>
                </div>
              </div>
              <div className="flex items-center gap-0.5 shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
                <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-neon-blue" onClick={() => navigate(`/character/${char.id}`)}>
                  <ExternalLink size={12} />
                </Button>
                <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-neon-purple" onClick={() => navigate(`/edit/${char.id}`)}>
                  <Pencil size={12} />
                </Button>
                <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-neon-rose" onClick={() => handleDeleteChar(char.id, char.name)} disabled={deletingId === char.id || !canEditAdminHub} title={!canEditAdminHub ? "Chỉ Admin/Op mới có quyền xoá" : undefined}>
                  {deletingId === char.id ? <Loader2 size={12} className="animate-spin" /> : <Trash size={12} />}
                </Button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );

  /* ---------- Render ---------- */
  return (
    <div className="flex-1 flex flex-col bg-oled-base overflow-hidden">
      {/* ═══════ Header — compact ChatPage style ═══════ */}
      <div className="shrink-0 flex items-center bg-oled-base border-b border-gray-border">
        <Link to="/admin" className="p-3 text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft size={20} />
        </Link>
        <div className="flex items-center gap-2.5 flex-1 min-w-0 py-2">
          <div className={`w-8 h-8 rounded-xl flex items-center justify-center shrink-0 ${
            cloneMode
              ? "bg-gradient-to-br from-neon-rose to-orange-500"
              : "bg-gradient-to-br from-neon-purple to-neon-rose"
          }`}>
            {cloneMode ? <ClipboardPaste className="text-white" size={15} /> : <Wand2 className="text-white" size={15} />}
          </div>
          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <h1 className="text-sm font-bold text-foreground truncate">
                {cloneMode ? "Clone Mode" : "AI Card Generator"}
              </h1>
              {generatedCard && (
                <Badge className="bg-green-500/15 text-green-400 border-green-500/30 text-[10px] px-1.5 py-0 shrink-0">
                  Card sẵn sàng
                </Badge>
              )}
            </div>
            <p className="text-[11px] text-muted-foreground truncate">
              {cloneMode ? "Dán mô tả → AI chuyển thành card" : "Tạo Character Card bằng LLM"}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-0.5 pr-2 shrink-0">
          {/* Review panel toggle */}
          {generatedCard && (
            <Tooltip>
              <TooltipTrigger asChild>
                <button
                  onClick={() => setReviewOpen(!reviewOpen)}
                  className={`p-2 transition-colors ${reviewOpen ? "text-green-400" : "text-muted-foreground hover:text-green-400"}`}
                >
                  {reviewOpen ? <PanelRightClose size={18} /> : <Eye size={18} />}
                </button>
              </TooltipTrigger>
              <TooltipContent side="bottom" className="bg-oled-surface border-gray-border text-foreground">
                {reviewOpen ? "Đóng panel duyệt" : "Duyệt & Xuất bản"}
              </TooltipContent>
            </Tooltip>
          )}
          {/* Clone mode toggle */}
          <Tooltip>
            <TooltipTrigger asChild>
              <button
                onClick={() => {
                  const next = !cloneMode;
                  setCloneMode(next);
                  if (next && messages.length === 0) {
                    toast.info("Clone Mode bật!", { description: "Dán mô tả nhân vật từ bất kỳ nguồn nào, AI sẽ tạo card." });
                  } else if (!next) {
                    toast.info("Clone Mode tắt");
                  }
                }}
                disabled={streaming}
                className={`p-2 transition-all ${
                  cloneMode
                    ? "text-neon-rose drop-shadow-[0_0_6px_rgba(255,38,100,0.4)]"
                    : "text-muted-foreground hover:text-neon-rose"
                }`}
              >
                <ClipboardPaste size={18} />
              </button>
            </TooltipTrigger>
            <TooltipContent side="bottom" className="bg-oled-surface border-gray-border text-foreground">
              {cloneMode ? "Tắt Clone Mode" : "Clone Mode — Dán text từ web"}
            </TooltipContent>
          </Tooltip>
          {/* History */}
          <Tooltip>
            <TooltipTrigger asChild>
              <button
                onClick={() => setHistoryOpen(true)}
                className="p-2 text-muted-foreground hover:text-neon-blue transition-colors"
              >
                <History size={18} />
              </button>
            </TooltipTrigger>
            <TooltipContent side="bottom" className="bg-oled-surface border-gray-border text-foreground">Lịch sử card</TooltipContent>
          </Tooltip>
          {/* Reset */}
          <Tooltip>
            <TooltipTrigger asChild>
              <button onClick={handleReset} className="p-2 text-muted-foreground hover:text-neon-rose transition-colors">
                <RotateCcw size={18} />
              </button>
            </TooltipTrigger>
            <TooltipContent side="bottom" className="bg-oled-surface border-gray-border text-foreground">Làm mới</TooltipContent>
          </Tooltip>
        </div>
      </div>

      <div className="shrink-0 px-3 py-2 border-b border-gray-border bg-oled-surface/30">
        <Tabs value={location.pathname === "/admin/chargen" ? "ai" : "manual"} className="w-full max-w-md">
          <TabsList className="w-full bg-oled-surface border border-gray-border h-auto">
            <TabsTrigger value="manual" asChild className="flex-1 data-[state=active]:bg-neon-purple/20 data-[state=active]:text-neon-purple">
              <Link to="/create">Tạo Card</Link>
            </TabsTrigger>
            <TabsTrigger value="ai" asChild className="flex-1 data-[state=active]:bg-neon-purple/20 data-[state=active]:text-neon-purple">
              <Link to="/admin/chargen">AI Charagen</Link>
            </TabsTrigger>
          </TabsList>
        </Tabs>
      </div>

      {/* ═══════ Main content area — flex row ═══════ */}
      <div className="flex-1 flex overflow-hidden">
        {/* ─── Chat column ─── */}
        <div className="flex-1 flex flex-col min-w-0">
          {/* Messages scroll area */}
          <div className="flex-1 overflow-y-auto scrollbar-thin py-4 space-y-4">
            {/* Empty state */}
            {messages.length === 0 && !streamBuffer && (
              <div className="flex flex-col items-center justify-center h-full gap-5 px-4">
                <motion.div
                  initial={{ scale: 0.8, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  transition={{ duration: 0.5, ease: "easeOut" }}
                  className={`w-20 h-20 rounded-3xl flex items-center justify-center ${
                    cloneMode
                      ? "bg-gradient-to-br from-neon-rose/20 to-orange-500/20 shadow-[0_0_30px_rgba(255,38,100,0.1)]"
                      : "bg-gradient-to-br from-neon-purple/20 to-neon-rose/20 shadow-[0_0_30px_rgba(176,38,255,0.1)]"
                  }`}
                >
                  {cloneMode ? (
                    <ClipboardPaste size={32} className="text-neon-rose" />
                  ) : (
                    <Wand2 size={32} className="text-neon-purple" />
                  )}
                </motion.div>
                <div className="text-center">
                  <p className="text-foreground font-semibold text-lg">
                    {cloneMode ? "Dán mô tả nhân vật" : "Mô tả nhân vật bạn muốn tạo"}
                  </p>
                  <p className="text-muted-foreground text-sm mt-1.5 max-w-md mx-auto">
                    {cloneMode
                      ? "Paste text từ wiki, web, forum... AI sẽ tự động phân tích và tạo thành Character Card"
                      : "Mô tả ý tưởng, tính cách, ngoại hình — AI sẽ tạo Character Card chất lượng cao cho bạn"
                    }
                  </p>
                </div>
                {!cloneMode ? (
                  <div className="flex flex-wrap gap-2 justify-center mt-1 max-w-lg">
                    {[
                      "Nữ chiến binh Samurai trầm lặng",
                      "Tiểu thư yandere giàu có",
                      "Bác sĩ ma cà rồng 500 tuổi",
                      "Thám tử tư lạnh lùng Sài Gòn",
                    ].map((s) => (
                      <motion.button
                        key={s}
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                        onClick={() => setInput(s)}
                        className="px-3.5 py-2 rounded-xl text-xs bg-oled-surface border border-oled-border text-muted-foreground hover:text-neon-purple hover:border-neon-purple/40 transition-all duration-200"
                      >
                        <Sparkles size={10} className="inline mr-1.5 opacity-50" />
                        {s}
                      </motion.button>
                    ))}
                  </div>
                ) : (
                  <div className="flex flex-wrap gap-1.5 justify-center text-[11px] text-muted-foreground mt-1">
                    {["Wiki pages", "Fandom", "Character.AI", "Chub.ai", "Forum posts", "Bất kỳ nguồn nào"].map((s) => (
                      <span key={s} className="px-2.5 py-1 rounded-full bg-oled-surface border border-oled-border">{s}</span>
                    ))}
                  </div>
                )}
              </div>
            )}

            {/* Message bubbles — ChatPage style */}
            <AnimatePresence>
              {messages.map((msg, i) => (
                <motion.div
                  key={i}
                  layout
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, height: 0, overflow: "hidden" }}
                  transition={{ duration: 0.3, ease: "easeOut" }}
                  className={`group flex gap-3 px-4 md:px-6 ${msg.role === "user" ? "justify-end" : "justify-start"}`}
                >
                  {/* AI Avatar */}
                  {msg.role === "assistant" && (
                    <div className="flex-shrink-0 mt-1">
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-semibold border ${
                        cloneMode
                          ? "bg-neon-rose/10 border-neon-rose/30 text-neon-rose"
                          : "bg-neon-purple/10 border-neon-purple/30 text-neon-purple"
                      }`}>
                        <Bot size={14} />
                      </div>
                    </div>
                  )}

                  <div className={`max-w-[80%] md:max-w-[70%] ${msg.role === "user" ? "order-first" : ""}`}>
                    {/* Name label */}
                    {msg.role === "assistant" && (
                      <span className={`text-[11px] ml-1 mb-1 block font-medium ${cloneMode ? "text-neon-rose/70" : "text-neon-purple/70"}`}>
                        {cloneMode ? "Clone AI" : "Card Generator"}
                      </span>
                    )}

                    {/* Bubble */}
                    <div
                      className={`rounded-2xl px-4 py-3 text-sm leading-relaxed transition-all duration-300 ${
                        msg.role === "user"
                          ? "bg-transparent border border-gray-border text-foreground hover:border-neon-blue hover:shadow-neon-blue"
                          : "bg-oled-surface text-foreground/90"
                      }`}
                      style={
                        msg.role !== "user"
                          ? {
                              background: cloneMode
                                ? "linear-gradient(135deg, rgba(255, 38, 100, 0.05) 0%, #0A0A0A 100%)"
                                : "linear-gradient(135deg, rgba(176, 38, 255, 0.05) 0%, #0A0A0A 100%)",
                            }
                          : undefined
                      }
                    >
                      {msg.role === "assistant" ? (
                        <span className="whitespace-pre-wrap">
                          <RoleplayMessage text={msg.content} />
                        </span>
                      ) : (
                        <p className="whitespace-pre-wrap">{msg.content}</p>
                      )}
                    </div>

                    {/* Actions row */}
                    <div className="flex items-center gap-1 mt-1 px-1">
                      {msg.content && (
                        <div className="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity">
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <button
                                onClick={() => handleCopyMsg(i, msg.content)}
                                className="p-1 rounded text-muted-foreground hover:text-foreground transition-colors"
                              >
                                {copiedIdx === i ? <Check size={12} className="text-green-400" /> : <Copy size={12} />}
                              </button>
                            </TooltipTrigger>
                            <TooltipContent side="top" className="bg-oled-surface border-gray-border text-foreground text-xs">
                              Sao chép
                            </TooltipContent>
                          </Tooltip>
                        </div>
                      )}
                    </div>
                  </div>

                  {/* User Avatar */}
                  {msg.role === "user" && (
                    <div className="flex-shrink-0 mt-1">
                      <div className="w-8 h-8 rounded-full bg-neon-blue/10 flex items-center justify-center border border-neon-blue/30">
                        <User size={14} className="text-neon-blue" />
                      </div>
                    </div>
                  )}
                </motion.div>
              ))}
            </AnimatePresence>

            {/* Streaming bubble */}
            {streamBuffer && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="flex gap-3 px-4 md:px-6 justify-start"
              >
                <div className="flex-shrink-0 mt-1">
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-semibold border animate-breathing ${
                    cloneMode ? "bg-neon-rose/10 border-neon-rose/30 text-neon-rose" : "bg-neon-purple/10 border-neon-purple/30 text-neon-purple"
                  }`}>
                    <Bot size={14} />
                  </div>
                </div>
                <div className="max-w-[80%] md:max-w-[70%]">
                  <span className={`text-[11px] ml-1 mb-1 block font-medium ${cloneMode ? "text-neon-rose/70" : "text-neon-purple/70"}`}>
                    {cloneMode ? "Clone AI" : "Card Generator"}
                  </span>
                  <div
                    className="rounded-2xl px-4 py-3 bg-oled-surface text-foreground/90"
                    style={{
                      background: cloneMode
                        ? "linear-gradient(135deg, rgba(255, 38, 100, 0.05) 0%, #0A0A0A 100%)"
                        : "linear-gradient(135deg, rgba(176, 38, 255, 0.05) 0%, #0A0A0A 100%)",
                    }}
                  >
                    <span className="whitespace-pre-wrap text-sm leading-relaxed">
                      <RoleplayMessage text={streamBuffer} />
                      <span className={`animate-blink font-mono ml-0.5 ${cloneMode ? "text-neon-rose" : "text-neon-purple"}`}>|</span>
                    </span>
                  </div>
                </div>
              </motion.div>
            )}

            {/* Streaming typing indicator */}
            {streaming && !streamBuffer && (
              <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="flex gap-3 px-4 md:px-6"
              >
                <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-semibold border animate-breathing ${
                  cloneMode ? "bg-neon-rose/10 border-neon-rose/30 text-neon-rose" : "bg-neon-purple/10 border-neon-purple/30 text-neon-purple"
                }`}>
                  <Bot size={14} />
                </div>
                <div className="bg-oled-surface rounded-2xl px-4 py-3 flex items-center gap-1">
                  <span className={`text-sm font-mono ${cloneMode ? "text-neon-rose/80" : "text-neon-purple/80"}`}>đang tạo</span>
                  <span className={`animate-blink font-mono text-sm ${cloneMode ? "text-neon-rose" : "text-neon-purple"}`}>|</span>
                </div>
              </motion.div>
            )}

            {/* Card detected notification */}
            {generatedCard && !reviewOpen && (
              <motion.div
                initial={{ opacity: 0, scale: 0.9, y: 10 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                className="flex justify-center px-4"
              >
                <button
                  onClick={() => setReviewOpen(true)}
                  className={`flex items-center gap-2.5 px-5 py-2.5 rounded-2xl text-sm font-medium transition-all duration-300 hover:scale-[1.02] active:scale-[0.98] ${
                    "bg-green-500/10 border border-green-500/30 text-green-400 hover:bg-green-500/20 hover:shadow-[0_0_20px_rgba(34,197,94,0.15)]"
                  }`}
                >
                  <CheckCircle2 size={16} />
                  Card đã sẵn sàng — Nhấn để duyệt "{generatedCard.data.name}"
                  <PanelRightOpen size={14} className="opacity-50" />
                </button>
              </motion.div>
            )}

            <div ref={chatEndRef} />
          </div>

          {/* ─── Input bar — ChatPage style ─── */}
          <div className="p-3 md:p-4 bg-oled-base border-t border-gray-border">
            <div className="max-w-3xl mx-auto">

              {/* ── Model settings row ── */}
              <div className="flex items-center gap-2 mb-2">
                <button
                  onClick={() => setModelSettingsOpen((v) => !v)}
                  className={`flex items-center gap-1.5 px-2.5 py-1 rounded-lg text-xs transition-all duration-200 border ${
                    modelSettingsOpen
                      ? "bg-neon-purple/10 border-neon-purple/40 text-neon-purple"
                      : "bg-oled-surface border-oled-border text-muted-foreground hover:text-neon-purple hover:border-neon-purple/30"
                  }`}
                >
                  <SlidersHorizontal size={11} />
                  <span>Model</span>
                  <ChevronDown
                    size={10}
                    className={`transition-transform duration-200 ${modelSettingsOpen ? "rotate-180" : ""}`}
                  />
                </button>
                {/* Show selected model name as a compact badge when collapsed */}
                {!modelSettingsOpen && (
                  <span className="text-[10px] text-muted-foreground truncate max-w-[200px]">
                    {selectedModel.split("/").pop()?.split(":")[0] ?? selectedModel}
                  </span>
                )}
              </div>

              {/* ── Collapsible model picker ── */}
              <AnimatePresence initial={false}>
                {modelSettingsOpen && (
                  <motion.div
                    key="model-settings"
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.2, ease: "easeInOut" }}
                    className="overflow-hidden mb-2"
                  >
                    <div className="bg-oled-surface border border-oled-border rounded-xl p-3 flex flex-col gap-2">
                      <p className="text-[10px] text-muted-foreground font-medium uppercase tracking-wide">Model AI</p>
                      <ModelCombobox value={selectedModel} onValueChange={handleModelChange} />
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>

              <div
                className={`flex items-end gap-2 bg-oled-surface rounded-2xl px-4 py-2 border transition-all duration-300 ${
                  cloneMode
                    ? "border-neon-rose/30 focus-within:border-neon-rose focus-within:shadow-[0_0_12px_rgba(255,38,100,0.15)]"
                    : "border-gray-border focus-within:border-neon-purple focus-within:shadow-neon-purple"
                }`}
              >
                <textarea
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder={cloneMode ? "Dán mô tả nhân vật từ website, wiki, forum..." : "Mô tả ý tưởng nhân vật..."}
                  disabled={streaming}
                  rows={1}
                  className="flex-1 bg-transparent text-foreground text-base md:text-sm resize-none outline-none placeholder:text-muted-foreground py-1.5 scrollbar-thin"
                  style={{ minHeight: "40px", maxHeight: "160px" }}
                  onInput={(e) => {
                    const el = e.currentTarget;
                    el.style.height = "auto";
                    el.style.height = Math.min(el.scrollHeight, 160) + "px";
                  }}
                />
                <div className="flex items-center gap-1 pb-0.5">
                  {streaming ? (
                    <motion.button
                      whileHover={{ scale: 1.1 }}
                      whileTap={{ scale: 0.95 }}
                      onClick={handleStop}
                      className="p-2.5 rounded-xl text-neon-rose transition-all duration-200 hover:bg-neon-rose/10"
                    >
                      <X size={20} />
                    </motion.button>
                  ) : (
                    <motion.button
                      whileHover={{ scale: 1.1 }}
                      whileTap={{ scale: 0.95 }}
                      onClick={handleSend}
                      disabled={!input.trim()}
                      className={`p-2.5 rounded-xl transition-all duration-200 disabled:opacity-30 ${
                        cloneMode
                          ? "text-neon-rose hover:bg-neon-rose/10 hover:shadow-[0_0_12px_rgba(255,38,100,0.2)]"
                          : "text-neon-purple hover:bg-neon-purple/10 hover:shadow-neon-purple"
                      }`}
                    >
                      <Send size={20} />
                    </motion.button>
                  )}
                </div>
              </div>
              <p className="text-[10px] text-muted-foreground text-center mt-2 hidden md:block">
                {cloneMode ? "Dán text → AI phân tích & tạo card tự động" : "Mô tả chi tiết để AI tạo card chất lượng cao hơn"}
              </p>
            </div>
          </div>
        </div>

        {/* ─── Desktop Review Panel — animated slide-in ─── */}
        <AnimatePresence>
          {!isMobile && reviewOpen && generatedCard && (
            <motion.div
              key="review-panel"
              initial={{ width: 0, opacity: 0 }}
              animate={{ width: 380, opacity: 1 }}
              exit={{ width: 0, opacity: 0 }}
              transition={{ duration: 0.25, ease: "easeInOut" }}
              className="border-l border-gray-border overflow-hidden"
              style={{ flexShrink: 0, maxWidth: 380 }}
            >
              <div style={{ width: 380 }} className="h-full">
                {reviewContent}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* ═══════ Mobile Review Sheet ═══════ */}
      {isMobile && (
        <Sheet open={reviewOpen && !!generatedCard} onOpenChange={(open) => { if (!open) setReviewOpen(false); }}>
          <SheetContent side="right" className="p-0 w-[90vw] max-w-md bg-oled-base border-gray-border">
            {reviewContent}
          </SheetContent>
        </Sheet>
      )}

      {/* ═══════ History Sheet (both desktop & mobile) ═══════ */}
      <Sheet open={historyOpen} onOpenChange={(open) => { if (!open) setHistoryOpen(false); }}>
        <SheetContent side="right" className="p-0 w-[90vw] max-w-md bg-oled-base border-gray-border">
          {historyContent}
        </SheetContent>
      </Sheet>
    </div>
  );
};

export default AdminCharGenPage;
